//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERRETERIATP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public string PRODUCTO { get; set; }
        public int PRODUCTOID { get; set; }
        public Nullable<decimal> PRECIOS { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CANTPRODUCTO { get; set; }
    }
}
