//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERRETERIATP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        public string PROVEEDOR { get; set; }
        public int PROVEEDORID { get; set; }
        public Nullable<int> PRODUCTOID { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<System.DateTime> FECHAENTREGA { get; set; }
        public Nullable<decimal> TOTALCOMPRADO { get; set; }
    }
}
